email_address:
  name: Email Address
  type: string
  default: example@example.com

email_name:
  default: Site Administrator
  type: string
  name: Email Name

smtp_address:
  default: "example.com"
  type: string
  name: SMTP Address

smtp_domain:
  default: "example.com"
  name: SMTP Domain

smtp_port:
  default: '25'
  name: SMTP Port

smtp_user_name:
  default: "example@example.com"
  name: SMTP User Name

smtp_password:
  default: "example"
  name: SMTP Password

tracking_code:
  type: text
  name: Tracking Code
  default: "<!-- Sample Tracking Code -->"

language_service:
  default: Spoken Languages
  name: Name of Service for Spoken Languages

payment_service:
  default: Accepted Payment Methods
  name: Name of Service for Accepted Payment Methods